Repository BookswapEPFL/Bookswap, pull requests merged in 2024-10, with the labels that each got.

#89 Feature: Implementation of the filter screen
  app/src/androidTest/java/com/android/bookswap/ui/map/FilterMapScreenTest.kt
  app/src/main/java/com/android/bookswap/data/DataBook.kt
  app/src/main/java/com/android/bookswap/ui/map/FilterMap.kt
  app/src/main/java/com/android/bookswap/ui/navigation/NavigationActions.kt
Labels: 4h

#86 fix keys in sonar properties
  app/build.gradle.kts
Labels: documentation, enhancement, 1h

#120 Feature add toasts to signal informations to user
  app/build.gradle.kts
  app/src/androidTest/java/com/android/bookswap/ui/book/addBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/bookAddition/BookAdditionChoiceScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/ISBNAddTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/utils/Books.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddISBNScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/chat/ChatScreen.kt
  app/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  gradle/libs.versions.toml
Labels: 1h

#129 Feature: apply the filter system also to the book's marker
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
Labels: 2h
