Repository BookswapEPFL/Bookswap, pull requests merged in 2024-12, with the labels that each got.

#297 Add Book picture handling in `BookDisplayComponent`
  app/src/androidTest/java/com/android/bookswap/ui/BookDisplayComponentTest.kt
  app/src/main/java/com/android/bookswap/resources/C.kt
  app/src/main/java/com/android/bookswap/ui/components/BookDisplayComponent.kt
Labels: 2h

#303 Fix adding book from ChatGPT and directly moves it to EditScreen
  app/src/androidTest/java/com/android/bookswap/ui/books/edit/EditBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/navigation/NavigationFromBookProfileToEditBookTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/model/BookFromChatGPT.kt
  app/src/main/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/edit/EditBookScreen.kt
  app/src/test/java/com/android/bookswap/model/BookFromChatGPTTest.kt
Labels: 4h

#330 Fix Get User
  app/src/main/java/com/android/bookswap/data/source/network/UserFirestoreSource.kt
Labels: 1h

#329 Fix app crash on first launch after login
  app/src/androidTest/java/com/android/bookswap/endtoend/NavigationBarEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/android/bookswap/model/map/Geolocation.kt
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
  app/src/test/java/com/android/bookswap/model/map/GeolocationTest.kt
Labels: 4h

#341 Fix adding book from ISBN not fetching the correct language
  app/src/androidTest/java/com/android/bookswap/ui/component/EntriesListBookTest.kt
  app/src/main/java/com/android/bookswap/data/DataBook.kt
  app/src/main/java/com/android/bookswap/data/source/api/GoogleBookDataSource.kt
  app/src/main/java/com/android/bookswap/model/map/BookFilter.kt
  app/src/main/java/com/android/bookswap/ui/books/BookProfile.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/components/EntriesListBookComponent.kt
  app/src/main/java/com/android/bookswap/ui/map/FilterMap.kt
  app/src/test/java/com/android/bookswap/data/source/api/GoogleBookDataSourceTest.kt
Labels: 1h

#336 Fix crash when trying to resolve address with NaN coords
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
Labels: 2h

#337 Book created from IBSN are sent to EditScreen
  app/src/androidTest/java/com/android/bookswap/ui/books/add/ISBNAddTest.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddISBNScreen.kt
Labels: 1h

#358 Fix map marker display
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/data/DataBook.kt
  app/src/main/java/com/android/bookswap/data/source/network/BookFirestoreSource.kt
  app/src/main/java/com/android/bookswap/data/source/network/DataConverter.kt
  app/src/test/java/com/android/bookswap/data/source/network/BooksFirestoreSourceTest.kt
Labels: 4h

#356 Add tests coverage for PhotoRequester
  app/src/androidTest/java/com/android/bookswap/model/PhotoRequesterTest.kt
  app/src/main/java/com/android/bookswap/model/PhotoRequester.kt
Labels: 4h
