Repository BookswapEPFL/Bookswap, pull requests merged in 2024-11, with the labels that each got.

#143 Added Apk build with working firebase login
  .github/workflows/buildApk.yml
  .gitignore
  app/build.gradle.kts
Labels: 3h

#163 Create complete app theme using Material3 Theme Builder
  app/src/main/java/com/android/bookswap/ui/theme/Color.kt
  app/src/main/java/com/android/bookswap/ui/theme/Theme.kt
  app/src/main/java/com/android/bookswap/ui/theme/Type.kt
Labels: documentation, enhancement, Refactor, MS2, 2h

#176 Refractor the whole app so all data type use UUID
  app/src/androidTest/java/com/android/bookswap/ui/books/add/addBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/UserProfileScreenTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/data/DataBook.kt
  app/src/main/java/com/android/bookswap/data/DataMessage.kt
  app/src/main/java/com/android/bookswap/data/DataPhoto.kt
  app/src/main/java/com/android/bookswap/data/DataUser.kt
  app/src/main/java/com/android/bookswap/data/repository/BookRepository.kt
  app/src/main/java/com/android/bookswap/data/repository/MessageRepository.kt
  app/src/main/java/com/android/bookswap/data/repository/PhotoRepository.kt
  app/src/main/java/com/android/bookswap/data/repository/UserRepository.kt
  app/src/main/java/com/android/bookswap/data/source/api/ChatGPTApiService.kt
  app/src/main/java/com/android/bookswap/data/source/network/BookFirestoreSource.kt
  app/src/main/java/com/android/bookswap/data/source/network/MessageFirestoreSource.kt
  app/src/main/java/com/android/bookswap/data/source/network/PhotoFirestoreSource.kt
  app/src/main/java/com/android/bookswap/data/source/network/UserFirestoreSource.kt
  app/src/main/java/com/android/bookswap/model/userViewModel.kt
  app/src/main/java/com/android/bookswap/ui/authentication/SignIn.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/books/edit/EditBookScreen.kt
  app/src/main/java/com/android/bookswap/ui/chat/ChatScreen.kt
  app/src/main/java/com/android/bookswap/ui/profile/UserProfile.kt
  app/src/test/java/com/android/bookswap/data/DataUserTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/BooksFirestoreRepositoryTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/ImageToDataSourceTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/PhotoFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/UserFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/model/chat/DataMessageFirestoreSourceTest.kt
Labels: Refactor, 3h

#192 Link Profile Screen to app navigation
  app/src/androidTest/java/com/android/bookswap/endtoend/NavigationBarEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/ui/MainActivityTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/ui/navigation/NavigationActions.kt
  app/src/test/java/com/android/bookswap/ui/navigation/NavigationActionsTest.kt
Labels: documentation, enhancement, MS2, 2h

#199 fix!: Fix BooksRepository and source
  app/src/androidTest/java/com/android/bookswap/endtoend/NavigationBarEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/ISBNAddTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/addBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/edit/EditBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/data/repository/BookRepository.kt
  app/src/main/java/com/android/bookswap/data/source/network/BookFirestoreSource.kt
  app/src/main/java/com/android/bookswap/model/map/BookManagerViewModel.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddISBNScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/books/edit/EditBookScreen.kt
  app/src/test/java/com/android/bookswap/data/source/api/GoogleBookDataSourceTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/BooksFirestoreRepositoryTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/BooksFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/model/map/BookManagerViewModelTest.kt
  app/src/test/java/com/android/bookswap/utils/BookUtils.kt
Labels: 4h

#203 Create book list view
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/bookswap/ui/components/BookDisplayComponent.kt
  app/src/main/java/com/android/bookswap/ui/components/BookListComponent.kt
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
Labels: enhancement, MS2, 4h

#194 Prevent unnecessary screen reloads when navigating to the current route
  app/src/main/java/com/android/bookswap/ui/navigation/NavigationActions.kt
  app/src/test/java/com/android/bookswap/ui/navigation/NavigationCurrentLocation.kt
Labels: 2h

#218 modify unit tests to use mockk instead of Mockito
  app/src/test/java/com/android/bookswap/data/source/api/GoogleBookDataSourceTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/PhotoFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/data/source/network/UserFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/model/chat/DataMessageFirestoreSourceTest.kt
  app/src/test/java/com/android/bookswap/model/chat/PermissionHandlerTest.kt
  app/src/test/java/com/android/bookswap/model/map/GeolocationTest.kt
  app/src/test/java/com/android/bookswap/ui/navigation/NavigationActionsTest.kt
Labels: 4h

#269 Refactor all non translated constants
  app/src/androidTest/java/com/android/bookswap/endtoend/AddBooksEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/endtoend/ChatEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/endtoend/NavigationBarEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/screen/EditProfileScreen.kt
  app/src/androidTest/java/com/android/bookswap/screen/UserProfileScreen.kt
  app/src/androidTest/java/com/android/bookswap/ui/MainActivityTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/authentication/LoginTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/BookProfileScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/ISBNAddTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/addBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/edit/EditBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/chat/ChatScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/chat/ListChatScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/map/FilterMapScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/navigation/BottomNavigationMenuTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/navigation/NavigationFromBookProfileToEditBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/NewUserScreenTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/data/DataMessage.kt
  app/src/main/java/com/android/bookswap/data/source/api/GoogleBookDataSource.kt
  app/src/main/java/com/android/bookswap/data/source/network/UserFirestoreSource.kt
  app/src/main/java/com/android/bookswap/model/chat/OfflineMessageStorage.kt
  app/src/main/java/com/android/bookswap/resources/C.kt
  app/src/main/java/com/android/bookswap/ui/authentication/SignIn.kt
  app/src/main/java/com/android/bookswap/ui/books/BookProfile.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddISBNScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/edit/EditBookScreen.kt
  app/src/main/java/com/android/bookswap/ui/chat/ChatScreen.kt
  app/src/main/java/com/android/bookswap/ui/chat/ListChat.kt
  app/src/main/java/com/android/bookswap/ui/components/BackButtonComponent.kt
  app/src/main/java/com/android/bookswap/ui/components/BookDisplayComponent.kt
  app/src/main/java/com/android/bookswap/ui/components/BookListComponent.kt
  app/src/main/java/com/android/bookswap/ui/components/TopAppBarComponent.kt
  app/src/main/java/com/android/bookswap/ui/map/FilterButton.kt
  app/src/main/java/com/android/bookswap/ui/map/FilterMap.kt
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
  app/src/main/java/com/android/bookswap/ui/navigation/BottomNavigationMenu.kt
  app/src/main/java/com/android/bookswap/ui/navigation/NavigationActions.kt
  app/src/main/java/com/android/bookswap/ui/profile/EditProfile.kt
  app/src/main/java/com/android/bookswap/ui/profile/NewUser.kt
  app/src/main/java/com/android/bookswap/ui/profile/UserProfile.kt
  app/src/main/java/com/android/bookswap/ui/profile/profileIcon.kt
  app/src/test/java/com/android/bookswap/model/chat/OfflineMessageStorageTest.kt
  app/src/test/java/com/android/bookswap/ui/navigation/NavigationActionsTest.kt
Labels: enhancement, Refactor, 4h

#275 Add common AppConfig available in all the Components
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/model/AppConfig.kt
  app/src/test/java/com/android/bookswap/model/AppConfigTest.kt
Labels: enhancement, 2h

#270 Add a button to the Map screen to recenter the camera on the current user's location
  app/src/androidTest/java/com/android/bookswap/endtoend/NavigationBarEndToEnd.kt
  app/src/androidTest/java/com/android/bookswap/ui/map/MapScreenTest.kt
  app/src/main/java/com/android/bookswap/ui/map/Map.kt
Labels: enhancement, 1h

#280 Make everything use the AppConfig UserViewModel
  app/src/androidTest/java/com/android/bookswap/ui/authentication/LoginTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/BookProfileScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/ISBNAddTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/books/add/addBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/navigation/NavigationFromBookProfileToEditBookTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/EditProfileScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/NewUserScreenTest.kt
  app/src/androidTest/java/com/android/bookswap/ui/profile/UserProfileScreenTest.kt
  app/src/main/java/com/android/bookswap/MainActivity.kt
  app/src/main/java/com/android/bookswap/model/chat/ContactViewModel.kt
  app/src/main/java/com/android/bookswap/model/userViewModel.kt
  app/src/main/java/com/android/bookswap/ui/authentication/SignIn.kt
  app/src/main/java/com/android/bookswap/ui/books/BookProfile.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddISBNScreen.kt
  app/src/main/java/com/android/bookswap/ui/books/add/AddToBook.kt
  app/src/main/java/com/android/bookswap/ui/books/add/BookAdditionChoiceScreen.kt
  app/src/main/java/com/android/bookswap/ui/chat/ListChat.kt
  app/src/main/java/com/android/bookswap/ui/profile/EditProfile.kt
  app/src/main/java/com/android/bookswap/ui/profile/NewUser.kt
  app/src/main/java/com/android/bookswap/ui/profile/UserProfile.kt
Labels: 4h
